# Generated by Django 6.0.6 on 2026-07-01 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(default='🌱', max_length=8)),
                ('color', models.CharField(default='#4F46E5', max_length=20)),
                ('min_difficulty', models.PositiveSmallIntegerField(default=1)),
                ('max_difficulty', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=80)),
                ('lesson_type', models.CharField(choices=[('quiz', 'Multiple Choice Quiz'), ('typing', 'Typing Recall'), ('wordle', 'Wordle'), ('dragdrop', 'Drag & Drop Match'), ('sudoku', 'Word Sudoku'), ('connections', 'Synonym Connections'), ('history', 'Word History'), ('test', 'Level Test')], max_length=20)),
                ('icon', models.CharField(default='📘', max_length=8)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('words', models.ManyToManyField(related_name='lessons', to='vocabulary.word')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.level')),
            ],
            options={
                'ordering': ['level__order', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('completed', 'Completed')], default='locked', max_length=10)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('best_score_pct', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
