# Generated by Django 6.0.6 on 2026-07-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, unique=True)),
                ('pronunciation_ipa', models.CharField(blank=True, max_length=100)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('preposition', 'Preposition')], default='noun', max_length=20)),
                ('definition', models.CharField(max_length=300)),
                ('example_sentence', models.CharField(blank=True, max_length=300)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Starter'), (2, 'Easy'), (3, 'Growing'), (4, 'Intermediate'), (5, 'Advanced'), (6, 'Expert'), (7, 'Master')], default=1)),
                ('etymology', models.TextField(blank=True, help_text='History / origin of the word')),
                ('origin_language', models.CharField(blank=True, max_length=60)),
                ('first_known_use', models.CharField(blank=True, max_length=60)),
                ('fun_fact', models.CharField(blank=True, max_length=300)),
                ('synonyms', models.ManyToManyField(blank=True, to='vocabulary.word')),
            ],
            options={
                'ordering': ['difficulty', 'text'],
            },
        ),
        migrations.CreateModel(
            name='WordOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
        ),
    ]
